import type { SpecialRule } from './types';

export const specialRules: SpecialRule[] = [
  {
    name: 'Fury of the Legion',
    description:
      'When a Model with this Special Rule makes a Shooting Attack with a bolter, the bolter gains the Heavy (FP) Special Rule until that Shooting Attack is fully resolved.',
  },
  {
    name: 'Officer of the Line',
    summary: 'Models with this Special Rule allow more Auxiliary Detachments to be included in an Army.',
    description: 'If a Model with this Special Rule is selected to fill a Command Slot in any Detachment in the Crusade Force Organization Chart, then the Controlling Player may select a number of Auxiliary Detachments equal to the value of X in the specific variant of this Special Rule instead of just one.'
  },
  {
    name: 'Pistol',
    summary: 'A Model may attack with two Weapons that have the Pistol Special Rule.',
    description:
      'During Step 3 of any Shooting Attack, a Player may choose to have a Model under their control make attacks with two Weapons rather than one if both Weapons have the Pistol Special Rule.',
  },
  {
    name: 'Critical Hit',
    summary:
      'Attacks made with the Critical Hit (X) Special Rule have a chance to automatically cause a wound and inflict 1 extra point of Damage.',
    description:
      "When any Hit Test is made for an attack with the Critical Hit (X) Special Rule, if the result of the Dice Roll, before any modifiers are applied, is equal to or greater than the value of X attached to this variant of the Critical Hit (X) Special Rule, then if a Hit is inflicted by that Hit Test, that Hit becomes a 'Critical Hit'.\n\nA Critical Hit automatically inflicts a wound without any dice being rolled, counting as the roll of a '6' for any variable Special Rules that might be triggered by a Wound Test, and increases the Damage of the Hit by +1.",
  },
  {
    name: 'Breaching',
    summary:
      'With a Weapon that has a Breaching (X) Special Rule there is a chance that a Wound Test may result in the Wound ignoring Armour Saves.',
    description:
      "When any Wound Test is made for an attack with the Breaching (X) Special Rule, if the result of the Dice roll, before any modifiers are applied, is equal to or greater than the value of X attached to this variant of the Breaching (X) Special Rule, then if a wound is inflicted by that Wound Test, that wound becomes a 'Breaching Wound'.\n\nA Breaching Wound is always treated as having an AP of 2 regardless of the Characteristics of the Weapon used to make the attack.",
  },
  {
    name: 'Overload',
    summary: 'Weapons with this Special Rule may inflict Hits on the Models making Shooting Attacks with them.',
    description:
      "When the Controlling Player declares that attacks will be made for a Model using a Weapon or Profile that has the Overload (X) Special Rule, any Hit Tests made for those attacks that result in a number that is equal to or less than the value of X attached to the variant of the Overload Special Rule that the Weapon had, before any modifiers are applied to the roll, are Misfires.\n\nFor Weapons that do not make Hit Tests, such as Weapons with the Template Special Rule, instead roll a number of Dice equal to the Firepower Characteristic of the Weapon used to make the attack after the attack has been declared and the number of Models hit is determined. Each Dice that results in a number equal to or less than the value of X attached to the variant of the Overload Special Rule that the Weapon had creates a Misfire. This does not affect the number of Hits on the Target Unit created by this attack.\n\nFor each Misfire, the Unit for which the Hit Tests were made suffer a Hit — these Hits must form a new Fire Group or Strike Group, referred to as the 'Misfire Group'.\n\nOnce the current Shooting Attack and any Reactions triggered by it have been fully resolved, the Misfire Group must be resolved. A Misfire Group is resolved in the same way as any other Fire Group or Strike Group, using the Profile of the Weapon used for the Fire Group or Strike Group it was created from. Wounds, Glancing Hits, or Penetrating Hits from this Misfire Group are allocated by the Controlling Player, and must be allocated to a Model that made attacks as part of the Fire Group or Strike Group that generated the Misfire Group. If a Hit from a Misfire Group is generated by an attack made by a Model with the Vehicle Type, then it is resolved against the lowest Armour Value from all of the Model's facings.\n\nHits, Wounds, or Casualties inflicted upon a Unit as a result of this Special Rule do not cause Leadership or Cool Checks, and Hits inflicted as part of a Misfire Group do not trigger any Special Rules that take effect as a result of a certain value on a Hit Test.",
  },
  {
    name: 'Template',
    summary:
      'Weapons and attacks with the Template Special Rule use the Flame Template to determine how many Models they Hit.',
    description:
      "When making attacks for a Weapon or other effect that has the Template Special Rule, or otherwise uses a Template, no Hit Tests are made for the attack. Instead, when directed to make Hit Tests for such an attack, a single Template is placed to determine how many Hits are generated. A Template must be placed so that its narrow end is touching the Base of the Model, the edge of a Model's Hull (if it has the Vehicle Type) or other point being used to make the attack, and so that no part of the Template covers or touches a friendly Model's Base, Hull or otherwise would inflict Hits on a friendly Model. Within these restrictions, the Player making the attack may place the Template in an orientation of their choosing as long as at least one Model from the original Target Unit remains under the Template. If the Template cannot be placed under these restrictions, then no attack may be made.\n\nOnce the Template has been placed, a number of Hits using the Profile of the Weapon or effect are inflicted on the Target Unit equal to the number of Models touched or covered by the Template. If more than one enemy Unit has Models that are touched or covered by the Template in its final position, Hits are inflicted on all such Units — Hits on Units other than the original target form a new Fire Group that must be placed to one side and used to resolve a separate Shooting Attack on the additional Target Unit once all attacks and Fire Groups from the original Shooting Attack have been fully resolved.\n\nWeapons with this Special Rule will have their Range Characteristic as 'Template'. If a Rule requires a number for the Range Characteristic (other than for making attacks), all Weapons and attacks with this Special Rule are considered to have a Range Characteristic of '8'.\n\nOther Templates\nIn some rare cases a Weapon may use a different Template than the standard Flame Template. In these cases the Template Rule may be expressed with a bracketed section stating which Template must be used. An example is the use of the Hellstorm Template, expressed as 'Template (Hellstorm)'. Weapons with the Template (Hellstorm) Special Rule are considered to have a Range Characteristic of '16' when a Rule requires such weapons to have a numbered Range Characteristic.",
  },
  {
    name: 'Deflagrate',
    summary: 'Unsaved Wounds inflicted by attacks with the Deflagrate (X) Special Rule can cause additional Hits.',
    description:
      'At the end of Step 9 of the Shooting Attack process for any Fire Group or Strike Group that includes Weapons with the Deflagrate (X) Special Rule, create a new Fire Group or Strike Group that must then be selected in Step 10 and resolved. This new Fire Group or Strike Group includes a number of Hits equal to the number of Unsaved Wounds caused by the Fire Group or Strike Group that triggered its creation. These Hits all have a Strength equal to the value of X attached to the variant of Deflagrate (X) Special Rule possessed by Weapons in the preceding Fire Group or Strike Group, an AP of \'—\', a Damage of 1 and no Special Rules.',
  },
  {
    name: 'Shred',
    summary: 'Attacks made with the Shred (X) Special Rule can sometimes inflict an extra point of Damage.',
    description:
      'When any Wound Test is made for an attack with the Shred (X) Special Rule, if the result of the Dice roll, before any modifiers are applied, is equal to or greater than the value of X attached to this variant of the Shred (X) Special Rule, then if a wound is inflicted by that Wound Test, the Damage of that wound is increased by 1. Note that the Shred (X) Special Rule may only be triggered by a Wound Test and has no effect when making an Armour Penetration Test.',
  },
  {
    name: "Duellist's Edge",
    summary: "A Weapon with the Duellist's Edge (X) Special Rule grants a bonus to Focus Rolls in Challenges.",
    description:
      "In Step 3 of the Challenge Sub-Phase, the Focus Step, if a Player has declared that the Model under their control will use a Weapon with the Duellist's Edge (X) Special Rule or has the Duellist's Edge (X) Special Rule, then that Player gains a bonus equal to the value of X on the Focus Roll.",
  },
  {
    name: 'Rending',
    summary:
      'With a Weapon that has the Rending (X) Special Rule, there is a chance that a Hit Test may result in an automatic wound.',
    description:
      "When any Hit Test is made for an attack with the Rending (X) Special Rule, if the result of the Dice roll, before any modifiers are applied, is equal to or greater than the value of X attached to this variant of the Rending (X) Special Rule, then if a Hit is inflicted by that Hit Test, that Hit becomes a 'Rending Hit'.\n\nWhen required to make a Wound Test for a Rending Hit, no Dice are rolled and the Wound Test succeeds automatically regardless of the Weapon's Strength or the Target's Toughness Characteristic. The Wound Test is treated as if the result had been '6' for the purposes of any Rules that would be triggered on certain results of a Wound Test. Wounds caused by a Rending Hit use the AP and Damage Characteristic of the Weapon used to make the attack and retain any Special Rules that Weapon had.\n\nIf the Target Unit includes any Models with the Vehicle Type, then this Special Rule has no effect.",
  },
  {
    name: 'Precision',
    summary: 'Attacks made with the Precision (X) Special Rule are allocated by the Attacking Player, not the Defender.',
    description:
      "When any Hit Test is made for an attack with the Precision (X) Special Rule, if the result of the Dice roll, before any modifiers are applied, is equal to or greater than the value of X attached to this variant of the Precision (X) Special Rule, then if a Hit is inflicted by that roll, that Hit becomes a 'Precision Hit'.\n\nThese Precision Hits must form a separate Fire Group or Strike Group. Wound Tests are made as normal for Precision Hits and cause Precision Wounds. When selecting a Target Model for a Fire Group or Strike Group made up of Precision Wounds, the attacking Player chooses which Model in the Target Unit will be the Target Model.\n\nNote that Models Engaged in a Challenge cannot use this Special Rule to allocate Hits to any Model other than the enemy Model Engaged in the same Challenge, and attacks made as Snap Shots, or for Weapons with the Blast (X), Barrage (X), Template or Reaping Blow (X) Special Rules, may never trigger the Precision (X) Special Rule.",
  },
  {
    name: 'Stun',
    summary:
      'Weapons and other attacks that have the Stun (X) Special Rule have a chance of inflicting the Stunned Status on the Target Unit.',
    description:
      'If a Shooting Attack made for a Weapon or Model with this Special Rule inflicts one or more Hits on a Target Unit, that Target Unit must make a Cool Check in the Morale Sub-Phase of the same Player Turn. If this Check is failed then all Models in the Unit gain the Stunned Status; if the Check is passed there is no further effect. The value of X attached to this Rule is applied as a negative modifier to the Cool Characteristic of Models in the Target Unit when making Checks caused by an attack with this Special Rule. If the attack includes multiple Weapons with different versions of this Special Rule the modifiers do not stack — use only the greatest modifier.',
  },
  {
    name: 'Panic',
    summary:
      'Weapons and other attacks that have the Panic (X) Special Rule have a chance of inflicting the Routed Status on the Target Unit.',
    description:
      'If a Shooting Attack made for a Weapon or Model with this Special Rule inflicts one or more wounds on a Target Unit, regardless of whether any Damage is inflicted, that Target Unit must make a Leadership Check in the Morale Sub-Phase of the same Player Turn. If this Check is failed then all Models in the Unit gain the Routed Status; if the Check is passed there is no further effect. The value of X attached to this Special Rule is applied as a negative modifier to the Leadership Characteristics of Models in the Target Unit when making Checks caused by an attack with this Special Rule. If the attack includes multiple Weapons with different variations of this Special Rule the modifiers do not stack — use only the greatest modifier.',
  },
  {
    name: 'Combi',
    summary: 'A Weapon with this Special Rule can fire multiple profiles simultaneously.',
    description:
      'Each time a Model makes a Shooting Attack with a Weapon Profile with this Special Rule, the Controlling Player can select another Profile from the same Weapon with this Special Rule and make attacks with it as part of the same Shooting Attack. Note that if that Profile also has the Limited (X) Special Rule, this does not allow it to be selected to make attacks more than the number of times equal to the value of that Special Rule.',
  },
  {
    name: 'Limited',
    summary: 'A Weapon with the Limited (X) Special Rule can only be used to attack a Limited number of times per Battle.',
    description:
      'A Weapon with the Limited (X) Special Rule may only be used to make attacks as part of a Shooting Attack or Combat a number of times equal to the value of X attached to the specific variant of the Special Rule. Each time it is used to make attacks, the Firepower Characteristic or Attacks Modifier Characteristic of the Weapon is not modified by this Special Rule — only the number of times it may be selected in a given Battle.',
  },
  {
    name: 'Melta',
    summary: 'This Special Rule increases the amount of Damage against Vehicles when Shooting Attacks are made within a specific range.',
    description:
      'If at least one Model in a Unit with the Vehicle Type that is targeted by a Shooting Attack made by a Model using a Weapon with this Special Rule is within a range equal to or less than the value specified by X, that attack has the Armourbane Special Rule and the Damage of Penetrating Hits caused by that attack is doubled.',
  },
  {
    name: 'Blast',
    summary: 'Attacks made with the Blast (X) Special Rule use a Blast Marker to determine how many Hits are caused.',
    description:
      'When making attacks with a Weapon that has the Blast (X) Special Rule, before any Hit Tests are made, a Blast Marker must first be placed. The Player must place the Blast Marker so that the hole in the middle is entirely over the base of any one model in the Target Unit. Once placed, the Player makes a Hit Test for the attack, and each Model from the Target Unit that is fully or partially under the Blast Marker suffers 1 Hit if the Hit Test is successful.\n\nIf any Models from Units other than the Target Unit are fully or partially covered by the Blast Marker, a new Fire Group must be created for those Hits and set to one side, resolved after the original Shooting Attack.\n\nIf the Hit Test is unsuccessful, no Hits are inflicted and the Player must make a Scatter Roll for the Blast Marker. Once the Scatter Roll has been made, one Hit is inflicted on a Unit for each Model from that Unit that is wholly or partially covered by the Blast Marker in its final position.',
  },
  {
    name: 'Pinning',
    summary:
      'Weapons and other attacks that have the Pinning (X) Special Rule have a chance of inflicting the Pinned Status on the Target Unit.',
    description:
      'If a Shooting Attack made for a Weapon or Model with this Special Rule inflicts one or more wounds on a Target Unit, regardless of whether any Damage is inflicted, that Target Unit must make a Cool Check in the Morale Sub-Phase of the same Player Turn. If this Check is failed then all Models in the Unit gain the Pinned Status; if the Check is passed there is no further effect. The value of X attached to this Special Rule is applied as a negative modifier to the Cool Characteristic of Models in the Target Unit when making Checks caused by an attack with this Special Rule. If the attack includes multiple Weapons with different versions of this Special Rule the modifiers do not stack — use only the greatest modifier.',
  },
  {
    name: 'Armourbane',
    summary: 'A Weapon with the Armourbane Special Rule counts Glancing Hits as Penetrating Hits.',
    description:
      'When making Armour Penetration tests for an attack with this Special Rule, a result that is equal to, or greater than, the target Armour Value inflicts a Penetrating Hit. A Weapon with this Special Rule can never inflict a Glancing Hit, and any Rule that would force them to do so instead inflicts a Penetrating Hit.',
  },
  {
    name: 'Detonation',
    summary: 'Weapons with this Special Rule can only attack Vehicles and immobile Models.',
    description:
      "A Weapon or attack with this Special Rule may only be selected during Step 2 of any Combat in the Fight Sub-Phase if the Unit making attacks is only Locked in Combat with enemy Units composed of Models with the Vehicle Type and Models with a Movement Characteristic of '-'. If a Unit is Locked in Combat with any enemy Units that include any Models that do not have the Vehicle Type or a Movement Characteristic of '0' or '-' then no Model may use a Weapon or other attack that has this Special Rule.\n\nA Weapon or other attack with this Special Rule may also be used to make attacks targeting a Model with the Building Type or a Terrain Piece that has a Toughness or Armour Characteristic.",
  },
  {
    name: 'Sire of the Dark Angels',
    summary: 'Grants special benefits to Dark Angels Detachments if certain Troops conditions are met.',
    description:
      'If a Model with this Special Rule is part of an Army, then the Controlling Player may apply the following Special Rules to all Auxiliary, Apex and Primary Detachments that have the same Faction Trait as the Model with this Special Rule:\n\nIf four or more Troops Battlefield Role Slots in the Primary Detachment of this Army are filled and these Slots contain at least one Tactical Squad Unit, at least one Assault Squad Unit and at least one Breacher Squad Unit, then all Force Organisation Slots with the Troops Battlefield Role in the Primary Detachment are considered Prime Slots.\n\nWhen the Controlling Player of a Model with this Special Rule makes a Reserve Roll for an Outrider Squadron Unit which only includes Models with the Dark Angels Trait or a Scimitar Jetbike Squadron Unit which only includes Models with the Dark Angels Trait, that Roll is modified by +1.',
  },
  {
    name: 'Bulky',
    summary: 'Models with this Special Rule take up more space on Transport Models.',
    description:
      'A Model with the Bulky (X) Special Rule does not use up 1 Point of Transport Capacity when it Embarks on a Model with the Transport Sub-Type. Instead it uses up a number of points of Transport Capacity equal to the value of X attached to the variant of the Bulky (X) possessed by that Model.',
  },
  {
    name: 'Eternal Warrior',
    summary: 'A Model with this Special Rule takes less Damage from attacks.',
    description:
      'When a Model with the Eternal Warrior (X) Special Rule is allocated an Unsaved Wound, the Damage of the Unsaved Wound is reduced by the value of X attached to the specific variant of the Eternal Warrior (X) Special Rule. The effects of this Special Rule cannot reduce the Damage of an Unsaved Wound to less than 1, regardless of the value of X.',
  },
  {
    name: 'The Angels of Death',
    summary: "Negative modifiers to Dark Angels' Leadership, Willpower, Cool and Intelligence are limited.",
    description:
      'Models with this Special Rule may never have their Leadership Characteristic modified to less than 6. Additionally, any variant of Fear (X) Special Rule may only reduce the Leadership, Willpower, Cool and Intelligence Characteristics of any Model with this Special Rule by a maximum of 1, regardless of the value of X.',
  },
  {
    name: 'Sword of the Order',
    summary: 'This Gambit may be chosen when using sword Weapons in Challenges.',
    description:
      "If this Gambit is selected, then as long as the Model under this Player's control is declared to be using a Chainsword, Power sword, Force sword, Paragon blade or Weapon with the Sword of the Order Trait, in Step 3 of the Challenge Sub-Phase, that Weapon's Attacks Modifier Characteristic is modified by -1 and it gains the Critical Hit (6+) Special Rule, or improves the value of X of an existing version of the Critical Hit (X) it already possesses by +1.",
  },
  {
    name: 'Paragon Type',
    summary: 'Paragons are extraordinary individual heroes whose Hits are allocated by their own Controlling Player.',
    description:
      'Any Hits inflicted by a Model with the Paragon Type, as part of either Shooting Attacks or in close combat, are allocated by the attacking Model\'s Controlling Player and not the Controlling Player of the Target Unit.\n\nModels with the Paragon Type may join and leave a Unit that includes Models with the Infantry Type, and Models with the Infantry Type may join and leave a Unit that includes one or more Models with the Paragon Type.\n\nModels with the Paragon Type may Embark and Disembark upon Models with the Transport Sub-Type.\n\nA Model with the Paragon Type may Issue and Accept Challenges.\n\nThe Controlling Player of a Unit that includes one or more Models with the Paragon Type may use the Characteristics of one of those Models to resolve any Characteristic Checks made for that Unit.\n\nIn Step 1 of the Resolution Sub-Phase, when deciding how many Models a Player controls in a Combat, a Model with the Paragon Type counts as a number of Models equal to that Model\'s Base Wounds Value.',
  },
  {
    name: 'Unique Sub-Type',
    summary: 'An Army may not include more than a single instance of a Model with the Unique Sub-Type.',
    description:
      'An Army may not include more than a single instance of a given Model with this Sub-Type.\n\nA Model with the Unique Sub-Type or a Unit composed entirely of Models with the Unique Sub-Type may not have any options other than those included on its Army List Profile selected for them.',
  },
  {
    name: 'Shock',
    summary:
      "Weapons with the Shock (X) Special Rule have a chance of inflicting Statuses on Vehicles even if it does not penetrate their armour.",
    description:
      "When making a Hit Test for a Weapon with this Special Rule against a Target Unit that includes any Models with the Vehicle Type or Walker Type, if any Hit Test results in a '5' or '6' before any modifiers are applied, then all Models with the Vehicle Type or Walker Type in the Target Unit gain a Status at the end of Step 11 of the Shooting Attack process or Step 10 of the Initiative Step process. The Status gained is indicated by the value of X attached to that variant of the Shock (X) Special Rule. If the Model already has the stated Status or the attack would apply the Status multiple times there is no additional effect; this Special Rule never causes a Model to lose Wounds or Hull Points. Hits inflicted by a Weapon with this Special Rule must still have Wound Tests or Armour Penetration Tests made for them.",
  },
];

export const specialRuleMap: Record<string, SpecialRule> = Object.fromEntries(
  specialRules.map((r) => [r.name, r])
);

/** Look up a special rule by exact name or by base name (strips trailing parenthetical). */
export function lookupRule(ruleName: string): SpecialRule | undefined {
  if (specialRuleMap[ruleName]) return specialRuleMap[ruleName];
  const base = ruleName.replace(/\s*\([^)]*\)\s*$/, '').trim();
  return specialRuleMap[base];
}
